[connections.snowflake]
account = "CKNHXSA-PM37442"
user = "Gayathri"
password = "Haniroyal@11"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
